name: Update README with current age

on:
  schedule:
    - cron: '28 6 * * *'  # Run daily at 06:07 UTC (== 2:07 AM EDT)
  workflow_dispatch:     # Manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Calculate precise age
        id: calc_age
        run: |
          # 👇 Your real birthdate
          BIRTH_DATE="2010-12-12"

          TODAY=$(date +'%Y-%m-%d')

          # Extract parts
          BIRTH_YEAR=$(date -d "$BIRTH_DATE" +'%Y')
          BIRTH_MONTH_DAY=$(date -d "$BIRTH_DATE" +'%m-%d')

          CURRENT_YEAR=$(date +'%Y')
          CURRENT_MONTH_DAY=$(date +'%m-%d')

          # Start with diff in years
          AGE=$((CURRENT_YEAR - BIRTH_YEAR))

          # If birthday hasn't happened yet this year, subtract 1
          if [[ "$CURRENT_MONTH_DAY" < "$BIRTH_MONTH_DAY" ]]; then
            AGE=$((AGE - 1))
          fi

          echo "AGE=$AGE" >> $GITHUB_ENV
          echo "Calculated age: $AGE"

      - name: Update readme.md
        run: |
          sed -i "s/<!-- _startage -->.*<!-- _endage -->/<!-- _startage --> $AGE <!-- _endage -->/" readme.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet; then
            git add readme.md
            git commit -m "chore: update age in README to $AGE"
            git push
          else
            echo "No changes to commit"
          fi
